import { createTheme, ThemeProvider } from '@mui/material/styles'
import Head from 'next/head'
import Footer from './Footer/Footer'
import Header from './Header'

const THEME = createTheme({
    typography: {
        fontFamily: `"Mulish","Roboto", "Helvetica", "Arial", sans-serif`,
    },
    palette: {
        text: {
            primary: '#1E3240',
        },
    },
})

export default function Layout({ children }) {
    return (
        <ThemeProvider theme={THEME}>
            <Head>
                <title>LAYAL</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <div>{children}</div>
            <Footer />
        </ThemeProvider>
    )
}
